# Generated by Django 5.0.14 on 2025-12-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_author_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
